// SPDX-FileCopyrightText: 2002-2026 PCSX2 Dev Team
// SPDX-License-Identifier: GPL-3.0+

// ARM64 EE Recompiler — MMI instructions (Phase 0: interpreter fallback)

#include "Common.h"
#include "R5900OpcodeTables.h"
#include "arm64/iR5900.h"
#include "arm64/iCore.h"

namespace Interp = R5900::Interpreter::OpcodeImpl::MMI;

namespace R5900 {
namespace Dynarec {
namespace OpcodeImpl {
namespace MMI {

	REC_FUNC(PLZCW);
	REC_FUNC(PMFHL);
	REC_FUNC(PMTHL);
	REC_FUNC(PSLLH);
	REC_FUNC(PSRLH);
	REC_FUNC(PSRAH);
	REC_FUNC(PSLLW);
	REC_FUNC(PSRLW);
	REC_FUNC(PSRAW);
	REC_FUNC(PADDW);
	REC_FUNC(PSUBW);
	REC_FUNC(PCGTW);
	REC_FUNC(PMAXW);
	REC_FUNC(PADDH);
	REC_FUNC(PSUBH);
	REC_FUNC(PCGTH);
	REC_FUNC(PMAXH);
	REC_FUNC(PADDB);
	REC_FUNC(PSUBB);
	REC_FUNC(PCGTB);
	REC_FUNC(PADDSW);
	REC_FUNC(PSUBSW);
	REC_FUNC(PEXTLW);
	REC_FUNC(PPACW);
	REC_FUNC(PADDSH);
	REC_FUNC(PSUBSH);
	REC_FUNC(PEXTLH);
	REC_FUNC(PPACH);
	REC_FUNC(PADDSB);
	REC_FUNC(PSUBSB);
	REC_FUNC(PEXTLB);
	REC_FUNC(PPACB);
	REC_FUNC(PEXT5);
	REC_FUNC(PPAC5);
	REC_FUNC(PABSW);
	REC_FUNC(PCEQW);
	REC_FUNC(PMINW);
	REC_FUNC(PADSBH);
	REC_FUNC(PABSH);
	REC_FUNC(PCEQH);
	REC_FUNC(PMINH);
	REC_FUNC(PCEQB);
	REC_FUNC(PADDUW);
	REC_FUNC(PSUBUW);
	REC_FUNC(PEXTUW);
	REC_FUNC(PADDUH);
	REC_FUNC(PSUBUH);
	REC_FUNC(PEXTUH);
	REC_FUNC(PADDUB);
	REC_FUNC(PSUBUB);
	REC_FUNC(PEXTUB);
	REC_FUNC(QFSRV);
	REC_FUNC(PMADDW);
	REC_FUNC(PSLLVW);
	REC_FUNC(PSRLVW);
	REC_FUNC(PMSUBW);
	REC_FUNC(PMFHI);
	REC_FUNC(PMFLO);
	REC_FUNC(PINTH);
	REC_FUNC(PMULTW);
	REC_FUNC(PDIVW);
	REC_FUNC(PCPYLD);
	REC_FUNC(PMADDH);
	REC_FUNC(PHMADH);
	REC_FUNC(PAND);
	REC_FUNC(PXOR);
	REC_FUNC(PMSUBH);
	REC_FUNC(PHMSBH);
	REC_FUNC(PEXEH);
	REC_FUNC(PREVH);
	REC_FUNC(PMULTH);
	REC_FUNC(PDIVBW);
	REC_FUNC(PEXEW);
	REC_FUNC(PROT3W);
	REC_FUNC(PMADDUW);
	REC_FUNC(PSRAVW);
	REC_FUNC(PMTHI);
	REC_FUNC(PMTLO);
	REC_FUNC(PINTEH);
	REC_FUNC(PMULTUW);
	REC_FUNC(PDIVUW);
	REC_FUNC(PCPYUD);
	REC_FUNC(POR);
	REC_FUNC(PNOR);
	REC_FUNC(PEXCH);
	REC_FUNC(PCPYH);
	REC_FUNC(PEXCW);

} // namespace MMI
} // namespace OpcodeImpl
} // namespace Dynarec
} // namespace R5900
